services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranking-tcc-app
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "3000:3000"
    environment:
      - APP_URL=https://appranking.taubatecountryclub.com.br
      - INTERNAL_APP_URL=http://localhost:3000
      - S3_ENDPOINT_INTERNAL=http://minio:9000
      - S3_PUBLIC_ENDPOINT
      - APP_TIMEZONE=America/Sao_Paulo
      - DATABASE_URL
      - JWT_SECRET
      - S3_ENDPOINT
      - S3_REGION
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_BUCKET
      - S3_PUBLIC_BASE_URL
      - S3_FORCE_PATH_STYLE
      - NEXT_PUBLIC_APP_NAME
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - SMTP_FROM
  minio:
    image: minio/minio
    container_name: ranking-tcc-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./docker/minio/data:/data
